'use strict';

function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

var React = _interopDefault(require('react'));
var ReactDOM = _interopDefault(require('react-dom'));

var instruments=[{trackerHost:"192.168.0.103",trackerName:"Small cells",trackerPort:8080,trackerPortWS:8081},{trackerHost:"192.168.0.104",trackerName:"Modules",trackerPort:8080,trackerPortWS:8081}];var database={host:"192.168.0.102",username:"",password:"",port:8086,db:"matahari"};var githubtokens={issuetracker:"81d7cb9ad6905e5a4e0cffbd4f47de13b0a2de4f"};var config = {instruments:instruments,database:database,githubtokens:githubtokens};

class BugReportForm extends React.Component{constructor(){super(...arguments), this.state={pending:!1,issueTitle:"",issue:""}, this.submitBug=this.submitBug.bind(this), this.handleInputChange=this.handleInputChange.bind(this);}handleInputChange(a){const b=a.target,c="checkbox"===b.type?b.checked:b.value,d=b.name;this.setState({[d]:c});}submitBug(){var a=JSON.stringify({title:this.state.issueTitle,body:this.state.issue}),b=new Headers;b.append("Content-Type","application/json"), b.append("Content-Length",a.length.toString()), b.append("Accept","application/vnd.github.v3+json"), this.setState({pending:!0,failed:!1}), fetch("https://api.github.com/repos/Candlelight-systems/app-issues/issues?access_token="+config.githubtokens.issuetracker,{method:"POST",headers:b,body:a}).then(a=>{var b=a.headers.get("content-type");if(b&&b.includes("application/json"))return a.json()}).then(a=>{console.log(a), this.setState({failed:!1,success:!0});}).catch(()=>{this.setState({failed:!0,success:!1});}).then(()=>{this.setState({pending:!1});});}render(){return React.createElement("div",{className:"container"},React.createElement("form",null,React.createElement("h3",null,"Report a bug"),React.createElement("div",{className:"form-group"},React.createElement("label",{htmlFor:"issueTitle"},"What is the name of your problem ?"),React.createElement("input",{type:"text",name:"issueTitle",value:this.state.issueTitle,id:"issueTitle",className:"form-control",placeholder:"Name of the issue",onChange:this.handleInputChange})),React.createElement("div",{className:"form-group"},React.createElement("label",{htmlFor:"issue"},"Tell us about your problem"),React.createElement("textarea",{id:"issue",name:"issue",value:this.state.issue,className:"form-control",rows:"12",placeholder:"Describe your issue here...",onChange:this.handleInputChange}),React.createElement("span",{id:"helpBlock",className:"help-block"},"Try to be as comprehensive while describing your issue. This will help us find and fix the issue as soon as possible")),React.createElement("div",{className:"form-group"},React.createElement("button",{type:"button",className:"btn btn-default "+(this.state.pending?"disabled":""),onClick:this.submitBug},"Submit bug")),this.state.failed&&React.createElement("p",{className:"bg-danger"},"Error in submitting the issue. Verify your internet connection. You may contact us at contact@candlelight-systems.com to report this problem"),this.state.success&&React.createElement("p",{className:"bg-success"},"Thank you for your contribution. We will review this issue as soon as possible.")))}}ReactDOM.render(React.createElement(BugReportForm,null),document.getElementById("root"));

//# sourceMappingURL=bugreport.js.map