language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - if [ $TRAVIS_PYTHON_VERSION == '2.6' ]; then pip install unittest2; fi
  - if [ $TRAVIS_PYTHON_VERSION == '3.2' ]; then pip install coverage==3.7.1; else pip install coverage; fi
  - pip install coveralls

script:
  - coverage run -p --source=pyvisa --omit="*test*","*compat*" setup.py test
  - coverage combine
  - coverage report -m

after_script:
  - coveralls --verbose
